"""empty message

Revision ID: 499ede3d5f03
Revises: 
Create Date: 2020-07-01 22:06:37.169163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499ede3d5f03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_score_point'), 'score', ['point'], unique=False)
    op.create_index(op.f('ix_score_timestamp'), 'score', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_timestamp'), table_name='score')
    op.drop_index(op.f('ix_score_point'), table_name='score')
    op.drop_table('score')
    # ### end Alembic commands ###
