"""empty message

Revision ID: 566a5bba85fc
Revises: 499ede3d5f03
Create Date: 2020-07-01 22:17:53.361630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566a5bba85fc'
down_revision = '499ede3d5f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_score_reason'), 'score', ['reason'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_reason'), table_name='score')
    op.drop_column('score', 'reason')
    # ### end Alembic commands ###
