"""add user name to point

Revision ID: 797af63c68fc
Revises: 566a5bba85fc
Create Date: 2020-07-04 12:51:47.559155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797af63c68fc'
down_revision = '566a5bba85fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_score_username'), 'score', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_username'), table_name='score')
    op.drop_column('score', 'username')
    # ### end Alembic commands ###
